### ISSUE TITLE
Issue with dub

### ISSUE THREAD

**Issue by askasys-code** [emoose/Arise-SDK#1]
Hello, I'm trying your mod and looks like everything is good except one thing.
Everytime I close and reopen the game, english dub is set by default... This is very annoying for those who play with the original japanese dub.

**Comment by emoose** [comment]
I think that's an issue with the intros being skipped, I posted a KeepIntros version on the 0.1.4 page which leaves them as they were, does that help at all? (https://github.com/emoose/Arise-SDK/releases/download/v0.1.4/KeepIntros-Arise-SDK-0.1.4.zip)

**Comment by askasys-code** [comment]
Thank you! The 0.1.5 version fix the issue.
